### ISSUE TITLE
requiring exported classes

### ISSUE THREAD

**Issue by timoweiss** [Microsoft/TypeScriptSamples#10]
Hey, i'm looking for a sample which imports classes from separated files.
When i do:

```javascript
export class MyClass {
    constructor() {
    }
}
```
And then in another file:

```javascript
import MyClass = require('./path/to/classes/MyClass')
```
To create an instance of `MyClass`, I need to call 
```javascript
new MyClass.MyClass()
```
And not simply `new MyClass()`.
Is there any way to fix this?

Thanks in advance

**Comment by DanielRosenwasser** [comment]
I think what you're looking for is

```TypeScript
import MyClass = require('./path/to/classes/MyClass').MyClass
```

Let us know if that fixes it!

**Comment by timoweiss** [comment]
Thanks, i switched to 1.5 alpha and added `default` after the export:
```javascript
export default class DatabaseService {
...
}
```
