### ISSUE TITLE
How to write test for Imageboard

### ISSUE THREAD

**Issue by btomala** [Microsoft/TypeScriptSamples#107]
How can I test `app.js` or `db.js` which mocha or other test framework?

**Comment by mhegazy** [comment]
Any [JavaScript test framework](https://en.wikipedia.org/wiki/List_of_unit_testing_frameworks#JavaScript) you like should just work. TypeScript is JavaScript, and it compiles down to plain JavaScript; no run-time library and no helper code. so when the compiler is done, you are left with just JS and any JS test framework or any JS build tool should work.
