### ISSUE TITLE
Why is super() called twice in the sample of Todo app? 

### ISSUE THREAD

**Issue by fspillner** [Microsoft/TypeScriptSamples#116]
Hi, 

I'm new related to TypeScript. I try to understand the sample code like here:

https://github.com/Microsoft/TypeScriptSamples/blob/master/todomvc/js/todos.ts#L204

I wonder why you don't call super(options) in the first line of the constructor. Instead of that you call super() with no arguments and a few lines later super(options) with arguments again. 

Can you explain me why? 

Thank you.

**Comment by DanielRosenwasser** [comment]
Looks like a bug introduced by #114. A fix is out in #117.

**Comment by fspillner** [comment]
Thank you <3

**Comment by DanielRosenwasser** [comment]
You're welcome! Thanks for the heads up!
