### ISSUE TITLE
Add new samples for packaging workflows

### ISSUE THREAD

**Issue by mhegazy** [Microsoft/TypeScriptSamples#13]
- [x] [JSPM](http://jspm.io/)
- [x] [browserify](http://browserify.org/)
- [x] [SystemJS](https://github.com/systemjs/systemjs)/[es6-module-loader](https://github.com/ModuleLoader/es6-module-loader)

**Comment by vladima** [comment]
SystemJS is covered in #15

**Comment by vladima** [comment]
JSPM is covered in #30

**Comment by vladima** [comment]
Browserify is covered in #31
