### ISSUE TITLE
jspm sample is out of date

### ISSUE THREAD

**Issue by aluanhaddad** [Microsoft/TypeScriptSamples#132]
The jspm sample uses TypeScript 1.8.10 and plugin-typescript 4.0.6.
It should be updated to demonstrate use with the latest versions.
Furthermore, while the sample contains a `tsconfig.json`, which can be read by an IDE, it is not used being passed to configure plugin-typescript to match. Demonstrating this would be useful and helps explain the relationship between TypeScript and plugin-typescript.
The `tsconfig.json` file should be used as per #20

**Comment by DanielRosenwasser** [comment]
We'd absolutely be willing to take a PR, and I think you would probably know what best practices to follow on this. 😃

**Comment by aluanhaddad** [comment]
@DanielRosenwasser thanks!

**Comment by DanielRosenwasser** [comment]
Thanks for the PR!
