### ISSUE TITLE
No licence information?

### ISSUE THREAD

**Issue by tcbrindle** [Microsoft/TypeScriptSamples#143]
Just for fun, I translated the raytracer example into [C++17, executing at compile-time](https://github.com/tcbrindle/raytracer.hpp).

As my work is based on the TypeScript version in this repo, I'd like to use the same licence as the original file -- but unfortunately I don't know what that is! There is no licence.txt (or equivalent) in this repo, and no text in the .ts file itself which might indicate under what terms it is usable.

I know legal stuff is a drag, but this is important to some people (especially big organisations like MS!). Please could you let me know what licence these examples are released under, and/or add some indication in this repo (such as a licence.txt file, or a note in the README).

**Comment by DanielRosenwasser** [comment]
Sorry about that - let me try to ping some people and get back to you about the TSSamples licensing policy.

**Comment by DanielRosenwasser** [comment]
Content in this repo should all have been published under the Apache-2.0 license. As a heads up, newer Microsoft content may have been published under the MIT license.

**Comment by tcbrindle** [comment]
Thanks very much
