### ISSUE TITLE
Typescript and JSPM question

### ISSUE THREAD

**Issue by paulvanbladel** [Microsoft/TypeScriptSamples#27]
referring to the sample https://github.com/Microsoft/TypeScriptSamples/tree/jspm/jspm

Is this sample supposed to work without doing a TS compile?

**Comment by nicky-lenaers** [comment]
I'm having the exact same question, since it's not working. Are we supposed to use plugin-typescript or something?

**Comment by DanielRosenwasser** [comment]
@vladima

**Comment by vladima** [comment]
I've updated the sample to work with the latest jspm

**Comment by paulvanbladel** [comment]
@vladima , thanks a lot. Works like a charm. I guess you can use now ts 1.5.x instead of the beta.
