### ISSUE TITLE
imageboard demo hangs, crashes

### ISSUE THREAD

**Issue by dcsan** [Microsoft/TypeScriptSamples#35]
just as an FYI the demo is a bit confusing...

i installed, compiled, ran the imageboard demo app
restored the db dump and we seem to have content there:
![image](https://cloud.githubusercontent.com/assets/514002/9432507/d185a572-49d8-11e5-8324-f66eca5b0a9d.png)

BUT
http://localhost:3000/

all seems extremely slow (I thought it was broken but left for awhile eventually get a response)
no watch pictures show. 

A good example of how to get going with ts and a recent express simple app would be great to have!

**Comment by fuyufjh** [comment]
One CSS in webpage could not be loaded any longer. This slow down all pages loading.

Just comment this line in `layout.jade` then everything works.
```
link(rel='stylesheet', href='http://cachedcommons.org/cache/960/0.0.0/stylesheets/960.css')
```

**Comment by mhegazy** [comment]
A PR to fix it would be appreciated..

@DanielRosenwasser ideas?

**Comment by DanielRosenwasser** [comment]
Thanks, I've got the fix, I'm just waiting on a DefinitelyTyped pull request to refresh this sample.

**Comment by DanielRosenwasser** [comment]
Fixed, thanks for the heads up @dcsan.
