### ISSUE TITLE
Some issues getting the Angula2 sample to work

### ISSUE THREAD

**Issue by federico-ardila** [Microsoft/TypeScriptSamples#45]
First I tried what the Readme files tell me to 

`npm install`

OK

But then when I try this:

`node node_modules/typescript/bin/tsc.js`

I get this:

`"Error cannot fin module ./pathtorrepo/angular2/node node_modules/typescript/bin/tsc.js"`

So I check the folder and the file there has no .js extension so I tried without the ".js"  and now I get a ton of compile errors, because tsc is now trying to compile itself in the node_modules folder, so I added `"exclude": ["node_modules"]` to tsconfig.json so I don't get any errors.  So now I go on an try to run it and all I get in the browser is "loading..." and this error in the console:

`"Potentially unhandled rejection [3] Error loading "todo" at https://registry.jspm.io/todo.js
Not Found: https://registry.jspm.io/todo.js (WARNING: non-Error used)"1 es6-module-loader@0.16.6.js:1:2570
[4]</</</</c<() es6-module-loader@0.16.6.js:1
i() es6-module-loader@0.16.6.js:1
u() es6-module-loader@0.16.6.js:1
`
So after a long time trying to find out what the error was, checking out the jspmUpdate branch  and trying many other things I found out that it works in Chrome and in Edge but not in Firefox (in either the developers edition, nor the stable versions). So could you guys either make it work on Firefox or at least write in the Readme that it doesn't work there so other people that use it as their default browser don't have to scratch their head as I did. Ah, and can you fix the .js ending thing as well as the tsconfig.json issues ?

**Comment by vladima** [comment]
#46 should address this
