### ISSUE TITLE
Not able to write Express Web Api using TypeScript.

### ISSUE THREAD

**Issue by natarajanmca11** [Microsoft/TypeScriptSamples#52]
Hi Team,

We are creating a pure Type Script based Express Seed Project in the following git repository. 
https://github.com/natarajanmca11/Express4-Seed.git
Please look at FullTypeScript branch. 
The problem is we are not able to create the sub module in type script. We could't utilize the express.d.ts types fully in this application. 

Please help us to create the sub module in typescript and how to inject in the main application. 

for example,
```
import {IRoute, RequestHandler}  from 'express';

export class Admin implements IRoute {
    path: string;
    stack: any;
    constructor() {
        this.path = '/api/Admin';
    }
    all(handler: RequestHandler) {
        return <IRoute>this;
    }
    get(handerl: RequestHandler): any {
        return{'Message' : 'all'};
    }
    post(handerl: RequestHandler): any {
        return <IRoute>this;
    }
    put(handerl: RequestHandler): any {
        return <IRoute>this;
    }
    delete(handerl: RequestHandler): any {
        return <IRoute>this;
    }
    patch(handerl: RequestHandler): any {
        return <IRoute>this;
    }
    options(handerl: RequestHandler): any {
        return <IRoute>this;
    }
    head(handerl: RequestHandler): any {
        return <IRoute>this;
    }
}
```
then inject in to the main application like below...
```
 self.Express.use(['/adm*n', '/manager'], new Admin());
```
the above Admin sub module does not throw any compile error but we don't know how to inject in main application.

also I need to replace `RequestHandler` with `(req: Request, res: Response, next: Function): any`.

Please guide me to move forward.

**Comment by DanielRosenwasser** [comment]
@natarajanmca11 I'm not strongly familiar with Express, and this repository isn't really the place for questions like this; these types of questions are better suited to sites like StackOverflow. Have you tried asking there?

However,

> We could't utilize the express.d.ts types fully in this application.

what exactly do you mean by this? 

> also I need to replace `RequestHandler` with `(req: Request, res: Response, next: Function): any`.

I'm not exactly sure what you mean, but if the typings are not accurate, feel free to get more up-to-date typings on [DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped), make the appropriate changes and send a pull request to them, or just use a type assertion as a work-around.

Also

> ```ts
    head(handerl: RequestHandler): any {
        return <IRoute>this;
    }
```

I'm not exactly sure why you're using a type assertion on `this` and making your methods return `any`, but you probably shouldn't need to do either of those things.
