### ISSUE TITLE
i can't run amd sample

### ISSUE THREAD

**Issue by zhishaofei3** [Microsoft/TypeScriptSamples#56]
I can't run amd sample

because default.htm not use any js file.

can you help me? thank you

**Comment by DanielRosenwasser** [comment]
Hi @zhishaofei3, did you try following the instructions in the README.md file?

When using [require.js](http://www.requirejs.org/docs/start.html) in an HTML `<script>` tag, there is an attribute called `data-main` that points to the base name of the JS file you want to use.

In our HTML file, our `data-main` is `"app"`, which means that require.js will try to load `app.js`. After compiling, you should have an `app.js` file.

**Comment by DanielRosenwasser** [comment]
I've updated the sample so that it's a little clearer where things start.

**Comment by zhishaofei3** [comment]
Oh, so, thank you
