### ISSUE TITLE
ImageBoard not 100% TS ?

### ISSUE THREAD

**Issue by daslicht** [Microsoft/TypeScriptSamples#57]
Hi,
whay do you use a callback function here without any typing ?

https://github.com/Microsoft/TypeScriptSamples/blob/master/imageboard/app.ts#L41

Wouldn't it be better to use something like this:

```
app.get('/findImages', ( req:Request, res:Response ) => {
```

?

**Comment by DanielRosenwasser** [comment]
I'm in the process of fixing up the imageboard sample.

**Comment by daslicht** [comment]
Very nice work ! I love TS!

**Comment by DanielRosenwasser** [comment]
Thanks! Glad to hear it. :smile:

**Comment by DanielRosenwasser** [comment]
Hey @daslicht, most of the parameters are now not implicitly typed as `any` - for anything that is, that's mostly due to lack of documentation. You can see where by adding the `noImplicitAny` flag when compiling.

**Comment by daslicht** [comment]
When I try to add a new Image the app crash with the following error:

```
{ result: { ok: 1, n: 1 },
  ops: 
   [ { user: 'lukeh',
       caption: 'COOL',
       imageUri: 'http://ansolas.de/assets/image/logo.svg',
       link: 'http://ansolas.de/assets/image/logo.svg',
       board: 'Flowers That I like',
       comments: [],
       _id: 564c4e1f903c20190471112f } ],
  insertedCount: 1,
  insertedIds: [ 564c4e1f903c20190471112f ] }
[TypeError: Cannot read property '_id' of undefined]
```

**Comment by DanielRosenwasser** [comment]
@daslicht I opened up #59 to track this. If you figure it out and you'd like to send a PR just give a heads up.

**Comment by daslicht** [comment]
thanks!
