### ISSUE TITLE
Property 'render' does not exist on type 'typeof __React'

### ISSUE THREAD

**Issue by barinbritva** [Microsoft/TypeScriptSamples#61]
I cloned repository, changed React version in <code>package.json</code>, because in version 0.14.x method render moved to ReactDOM:
<code>
// ...
"react": "0.13.3",
// ...
</code>
Then:
<code>
npm install
node node_modules/typescript/bin/tsc
</code>
Error:
<code>
src/app.tsx(19,11): error TS2339: Property 'render' does not exist on type 'typeof __React'.
</code>

**Comment by DanielRosenwasser** [comment]
I think this sample was created with 0.13.3 in mind, and so the typings used for it make sense at it stands, though we should probably update the sample.

@RyanCavanaugh or @johnnyreilly, if it's not too much trouble, maybe one of you guys can take a look at this when you get the chance.

**Comment by johnnyreilly** [comment]
Yup - I'm planning to take a look at this

**Comment by DanielRosenwasser** [comment]
I think this can be closed now. Thanks @johnnyreilly!
