### ISSUE TITLE
Replace alert() with console.log()

### ISSUE THREAD

**Issue by parambirs** [Microsoft/TypeScriptSamples#64]
Hi there,

In some of the samples, `alert()` is used for printing debugging info. Would it be better to replace such statements with `console.log`?

I'm happy to raise a pull request for some of the changes I've made while trying out the samples on my machine.

Thanks
Param

**Comment by DanielRosenwasser** [comment]
Hi @parambirs - I think the sample was acquired from the playground/walkthrough where code would get executed in the browser. `alert` is more explicit there for users than `console.log`. We'd be happy to take a pull request!

**Comment by DanielRosenwasser** [comment]
Closed by #66.
