### ISSUE TITLE
imageboard: TypeError: Property 'engine' of object #<View> is not a function

### ISSUE THREAD

**Issue by mictadlo** [Microsoft/TypeScriptSamples#7]
Hi,
I had to remove `>=` from the `package.json` in order to get rid off this error:

    $ mongod --dbpath /home/u/databases
    $ npm install
    $ tsc --sourcemap --module commonjs app.ts
    $ node app.js                             
    { [Error: Cannot find module '../build/Release/bson'] code: 'MODULE_NOT_FOUND' }
    js-bson: Failed to load c++ bson extension, using pure JS version
    ========================================================================================
    =  Please ensure that you set the default write concern for the database by setting    =
    =   one of the options                                                                 =
    =                                                                                      =
    =     w: (value of > -1 or the string 'majority'), where < 1 means                     =
    =        no write acknowledgement                                                       =
    =     journal: true/false, wait for flush to journal before acknowledgement             =
    =     fsync: true/false, wait for flush to file system before acknowledgement           =
    =                                                                                      =
    =  For backward compatibility safe is still supported and                              =
    =   allows values of [true | false | {j:true} | {w:n, wtimeout:n} | {fsync:true}]      =
    =   the default value is false which means the driver receives does not                =
    =   return the information of the success/error of the insert/update/remove            =
    =                                                                                      =
    =   ex: new Db(new Server('localhost', 27017), {safe:false})                           =
    =                                                                                      =
    =   http://www.mongodb.org/display/DOCS/getLastError+Command                           =
    =                                                                                      =
    =  The default of no acknowledgement will change in the very near future                =
    =                                                                                      =
    =  This message will disappear when the default safe is set on the driver Db           =
    ========================================================================================

    /home/u/tmp/TypeScriptSamples/imageboard/app.js:9
    app.configure(function () {
        ^
    TypeError: Object function (req, res, next) {
        app.handle(req, res, next);
      } has no method 'configure'
        at Object.<anonymous> (/home/u/tmp/TypeScriptSamples/imageboard/app.js:9:5)
        at Module._compile (module.js:456:26)
        at Object.Module._extensions..js (module.js:474:10)
        at Module.load (module.js:356:32)
        at Function.Module._load (module.js:312:12)
        at Function.Module.runMain (module.js:497:10)
        at startup (node.js:119:16)
        at node.js:929:3

However, now I get a new error:

    $ node app.js
    Demo Express server listening on port 3000 in development mode
    []
    TypeError: Property 'engine' of object #<View> is not a function
        at View.render (/home/u/tmp/TypeScriptSamples/imageboard/node_modules/express/lib/view.js:75:8)
        at Function.app.render (/home/u/tmp/TypeScriptSamples/imageboard/node_modules/express/lib/application.js:505:10)
        at ServerResponse.res.render (/home/u/tmp/TypeScriptSamples/imageboard/node_modules/express/lib/response.js:717:7)
        at /home/u/tmp/TypeScriptSamples/imageboard/routes/index.js:5:13
        at /home/u/tmp/TypeScriptSamples/imageboard/db.js:34:13
        at /home/u/tmp/TypeScriptSamples/imageboard/node_modules/mongodb/lib/mongodb/cursor.js:129:9
        at /home/u/tmp/TypeScriptSamples/imageboard/node_modules/mongodb/lib/mongodb/cursor.js:171:11
        at /home/u/tmp/TypeScriptSamples/imageboard/node_modules/mongodb/lib/mongodb/cursor.js:463:35
        at Cursor.close (/home/u/tmp/TypeScriptSamples/imageboard/node_modules/mongodb/lib/mongodb/cursor.js:682:5)
        at Cursor.nextObject (/home/u/tmp/TypeScriptSamples/imageboard/node_modules/mongodb/lib/mongodb/cursor.js:463:17)

How is it possible resolve the above TypeError?

Thank you in advance.

**Comment by DanielRosenwasser** [comment]
Seems to be related to this:

http://stackoverflow.com/questions/11810451/error-using-express-for-nodejs-engine-of-object-view-is-not-a-function

Give it a try, let us know if it works.

**Comment by mictadlo** [comment]
Was the solution at stackoverflow [post](http://stackoverflow.com/a/11819484) to use  only `cd imageboard && npm install`? If yes then it did not work for me:

    [u@wp TypeScriptSamples]$ rm -rf imageboard/node_modules
    [u@wp TypeScriptSamples]$ cd imageboard && npm install
    
    > bson@0.0.4 install /home/u/tmp/TypeScriptSamples/imageboard/node_modules/mongodb/node_modules/bson
    > node install.js

    ================================================================================
    =                                                                              =
    =  To install with C++ bson parser do <npm install mongodb --mongodb:native>   =
    =                                                                              =
    ================================================================================
    ejs@0.5.0 node_modules/ejs

    jade@0.0.1 node_modules/jade

    mongodb@1.0.0 node_modules/mongodb
    └── bson@0.0.4

    express@3.0.0 node_modules/express
    ├── methods@0.0.1
    ├── fresh@0.1.0
    ├── range-parser@0.0.4
    ├── cookie@0.0.4
    ├── crc@0.2.0
    ├── commander@0.6.1
    ├── mkdirp@0.3.3
    ├── debug@2.1.1 (ms@0.6.2)
    ├── send@0.1.0 (mime@1.2.6)
    └── connect@2.6.0 (pause@0.0.1, bytes@0.1.0, send@0.0.4, formidable@1.0.11, qs@0.5.1)
    [u@wp imageboard]$ tsc --sourcemap --module commonjs app.ts
    [u@wp imageboard]$ node app.js
    Demo Express server listening on port 3000 in development mode
    []
    TypeError: Property 'engine' of object #<View> is not a function
        at View.render (/home/u/tmp/TypeScriptSamples/imageboard/node_modules/express/lib/view.js:75:8)
        at Function.app.render (/home/u/tmp/TypeScriptSamples/imageboard/node_modules/express/lib/application.js:505:10)
        at ServerResponse.res.render (/home/u/tmp/TypeScriptSamples/imageboard/node_modules/express/lib/response.js:717:7)
        at /home/u/tmp/TypeScriptSamples/imageboard/routes/index.js:5:13
        at /home/u/tmp/TypeScriptSamples/imageboard/db.js:34:13
        at /home/u/tmp/TypeScriptSamples/imageboard/node_modules/mongodb/lib/mongodb/cursor.js:129:9
        at /home/u/tmp/TypeScriptSamples/imageboard/node_modules/mongodb/lib/mongodb/cursor.js:171:11
        at /home/u/tmp/TypeScriptSamples/imageboard/node_modules/mongodb/lib/mongodb/cursor.js:463:35
        at Cursor.close (/home/u/tmp/TypeScriptSamples/imageboard/node_modules/mongodb/lib/mongodb/cursor.js:682:5)
        at Cursor.nextObject (/home/u/tmp/TypeScriptSamples/imageboard/node_modules/mongodb/lib/mongodb/cursor.js:463:17)

**Comment by DanielRosenwasser** [comment]
Hey @mictadlo, this should be fixed now.

**Comment by mictadlo** [comment]
Thank you it works!
