### ISSUE TITLE
404 NotFound when using TypeScript Pallax Sample

### ISSUE THREAD

**Issue by DanielRosenwasser** [Microsoft/TypeScriptSamples#74]
_From @veleek on February 20, 2016 21:34_

Attempting to load the Parallax Starfield typescrypt sample fails in Chrome.

Sample: http://www.typescriptlang.org/Sample/jquery/parallax.html gives a 404 when loading /Sample/jquery/starfield2.png.

On Chrome this appears to break the sample, but the same 404 appears on other browsers, so maybe it's a read herring.

_Copied from original issue: Microsoft/TypeScript#7171_

**Comment by veleek** [comment]
After Daniel moved this bug to the proper repository I was able to find the code that referred to this and it has already been fixed in the repository by commit 6b8d621.

**Comment by DanielRosenwasser** [comment]
Thanks for the heads up! We'll be updating the website content soon.
