### ISSUE TITLE
error TS5023: Unknown option 'watch' - error TS5007: Cannot resolve referenced file: 'app'.

### ISSUE THREAD

**Issue by Abdelkrim** [Microsoft/TypeScriptSamples#77]
I have executed the setup 
```
npm install typescript -g
npm install tsd -g
```

everything went well until I executed the ```tsc --watch --p app```.

```
$ tsc --watch --p app
error TS5023: Unknown option 'watch'
Use the '--help' flag to see options.
error TS5023: Unknown option 'p'
Use the '--help' flag to see options.
error TS5007: Cannot resolve referenced file: 'app'.
```

 the same error occurs with ```tsc --watch --p e2e-tests```

```
$ tsc --watch --p e2e-tests
error TS5023: Unknown option 'watch'
Use the '--help' flag to see options.
error TS5023: Unknown option 'p'
Use the '--help' flag to see options.
error TS5007: Cannot resolve referenced file: 'e2e-tests'.
```

thank you in advance for your help

**Comment by mhegazy** [comment]
can you do `where tsc`. i suspect you have a `tsc` in your path that points to an older tsc.

**Comment by DanielRosenwasser** [comment]
Also let us know what version you have with `tsc --version`.

**Comment by Abdelkrim** [comment]
$  tsc --version
Version 1.0.3.0

$ where tsc
C:\Program Files (x86)\Microsoft SDKs\TypeScript\1.0\tsc.exe
C:\Program Files (x86)\Microsoft SDKs\TypeScript\1.0\tsc.js

**Comment by DanielRosenwasser** [comment]
You'll need to edit your system's `PATH` variable to make `C:\Program Files (x86)\Microsoft SDKs\TypeScript\1.8` (or `C:\Users\[YOUR USERNAME]\AppData\Roaming\npm\` if you're using npm) come before that.

**Comment by hervegbedji** [comment]
Hello Guys came through this issue and am currently following the above mentioned advices. Now that the the PATH is edited. What's normally next. Uninstalling npm and tsc and running the installs again or .. ?
