### ISSUE TITLE
demo: browserify is not working now.

### ISSUE THREAD

**Issue by lewgun** [Microsoft/TypeScriptSamples#82]
I had followd the step in the README.md.

.... 
D:\TypeScriptSamples\browserify>npm run tsc

> typescript-browserify@1.0.0 tsc D:\TypeScriptSamples\browserify
> node node_modules/typescript/bin/tsc.js

module.js:338
    throw err;
    ^

Error: Cannot find module 'D:\TypeScriptSamples\browserify\node_modules\typescript\bin\tsc.js'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:286:25)
    at Function.Module.runMain (module.js:475:10)
    at startup (node.js:117:18)
    at node.js:951:3

npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "tsc"
npm ERR! node v4.1.1
npm ERR! npm  v2.14.4
npm ERR! code ELIFECYCLE
npm ERR! typescript-browserify@1.0.0 tsc: `node node_modules/typescript/bin/tsc.js`
npm ERR! Exit status 1

**Comment by DanielRosenwasser** [comment]
#83 has a simple fix.

**Comment by mhegazy** [comment]
should be fixed now.
