### ISSUE TITLE
webpack ts-loader sample

### ISSUE THREAD

**Issue by GaryB432** [Microsoft/TypeScriptSamples#99]
I didn't see a [webpack](https://webpack.github.io/) sample so I made one (using [ts-loader](https://www.npmjs.com/package/ts-loader)) at https://github.com/GaryB432/webpack-typescript.  I can put it into a PR if you're interested.

**Comment by mhegazy** [comment]
Does this work-through match you expectations: https://github.com/Microsoft/TypeScript-Handbook/blob/master/pages/quick-start/react-webpack.md ?

**Comment by GaryB432** [comment]
I overlooked that one, unaware that the handbook also had samples/starters. It sure is nicely documented. Mine does not include React, just webpack and ts-loader. I was keeping it stripped down like greeter.

**Comment by mhegazy** [comment]
We intend to publish these to typescriptlang.org soon and to the samples repo. So of this does the trick then I would say we do not need another sample.

**Comment by GaryB432** [comment]
Sounds right.  Thanks for your attention.
